name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.x'
          channel: 'stable'
          cache: true

      - name: Update Android SDK configuration
        run: |
          # Update compileSdk to 35
          sed -i 's/compileSdk = [0-9]*/compileSdk = 35/g' android/app/build.gradle
          sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 35/g' android/app/build.gradle
          
          # Ensure targetSdk is set appropriately
          sed -i 's/targetSdk = [0-9]*/targetSdk = 35/g' android/app/build.gradle
          sed -i 's/targetSdkVersion [0-9]*/targetSdkVersion 35/g' android/app/build.gradle

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos || true

      - name: Build ARM64-v8a APK
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Build Universal APK
        run: flutter build apk --release

      - name: Rename APKs
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk output/reins-arm64-v8a.apk
          cp build/app/outputs/flutter-apk/app-release.apk output/reins-universal.apk

      - name: Upload ARM64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: reins-arm64-v8a
          path: output/reins-arm64-v8a.apk
          if-no-files-found: error

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: reins-universal
          path: output/reins-universal.apk
          if-no-files-found: error

      - name: Create Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            output/reins-arm64-v8a.apk
            output/reins-universal.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}